### ISSUE TITLE
Add project board automation for auto adding issues

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab-bot#200]
This feature is quite a bit different than what we have done so far. If we take the mission of the bot more broadly as "custom automation in GitHub for the InstructLab project", then I think this fits, but I'm interested in input on that.

We are using project boards for tracking purposes.  Some boards (backend, for example) span several repos that represent a logical group of work. Another example is a documentation board that tracks doc things across repos.

https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/adding-items-automatically

While working on the backend board, I noticed we are limited to 5 workflows for auto adding items to the project. In other words, we can only auto-add from 5 repos to a single project. Worse, I think this limit is going to drop back to 1 if we move from GitHub Teams (paid) to a free plan once it's fully open.

This is all quite annoying, and I don't think it would be hard to just do this ourselves in the bot.

```yaml
project_auto_add:
    board_name:
        - instruct-lab/repo1
        - instruct-lab/repo2
    board_name:
        - instruct-lab/repo3
        - instruct-lab/repo4
        - instruct-lab/repo5
```

We can act on issue created / pull request created events to auto add to the projects per the configuration.

This is optional, but we could also consider a periodic task that would check to see if any got missed, like when the bot was down for some reason. That's more complicated and maybe not worth it. Maybe there's even a reason folks would remove issues from a board if they think they shouldn't be on there for some reason.
